# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/



#######################################################################
# Site settings
#######################################################################

skin: light #Light(Default), Dark
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lumunix.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "lumunix/lumunix.github.io" # GitHub username/repo-name
analytics: G-B52EHKF77Y # Google Analytics
#######################################################################
# User Settings
#######################################################################
user:
  name: Lumunix
  image: Icon.png
  about: Scree, I am a software engineer that specializes in automation.
  contact:
    twitter: Lumunix
    github: Lumunix
    youtube: Lumunix
    linkedin:
    twitch: lumunix
    facebook:
    instagram: lum_unix
    email: lumunix@icloud.com



#####################################################################
# Site Feature Settings
#####################################################################
preferences:
  search:
    enabled: true
  wiki_style_link: # This property handles wiki style links '[['
    enabled: true
  sidenotes:
    enabled: true
  transclusion:
    enabled: true
  image:
    enabled: true
  pagepreview:
    enabled: true
  highlighting:
    enabled: true
    color: DAEDFF

  backlinks:
    enabled: true
  related:
    enabled: true # This enables the posts that are related to each other by tags
  wrapping:
    enabled: true
  pagination:
    system: infinitescroll ##infinitescroll (default), "infinitescroll", "pagination"
  contextmenu:
    enabled: true
    copylink:
      enabled: true
    newtab:
      enabled: true
    backlinks:
      enabled: true
    related:
      enabled: true
  flashcards:
    enabled: true
  reCaptcha:
    # Using a google account create a reCaptcha at https://www.google.com/recaptcha/admin
    enabled: true
    siteKey: 6LeLYEYaAAAAAFGdotkfMHnCB3iA1hFY1dJmcoSy
    secret: KMFMK/JphRpu1sXpWls+8HlOsAHT/YV+U4qylPp+mkz4St1WStQGj2ccaJunnpcv3yXAfTh/utP4P9Wa+HuV7xqzkh5BWbYMeZjx9FNC5iVYSsq9QME3/cZnWL3TEDFkYpjBLC2VDmz81cepo3zSdMrGhSgmql6IYoQzgkFa17M=
  comments:
    system: staticman #false (default), "disqus", "staticman"
    disqus:
      shortname: lumunix # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
    staticman:
      #See additional options in staticman.yml
      branch: "master" # "master"
      staticman_url: "https://api.staticman.net/v3/entry/github/lumunix/lumunix.github.io/master/comments"


#####################################################################
# Build Settings
# plugins, markdown,
#####################################################################
encoding: utf-8
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-tidy
  - jekyll-paginate

markdown: kramdown
paginate: 6
paginate_path: "/page/:num"

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: katex
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: Post
      permalink: /posts/:title
      content-type: post



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
